### PR TITLE
New version on my fork

### PR DESCRIPTION
**Pull request by greenbigfrog**

### CODE REVIEW

**Comment by greenbigfrog** [comment]
I'm maintaining a working version on my fork

**Comment by citizen428** [comment]
Thanks for doing this @greenbigfrog, I somehow missed this PR until now 😢

**Comment by citizen428** [comment]
@pynixwang Regarding the 200 code plus JSON error: that's part of how Bitcoin RPC works. There are discussions in their issues as to the rationale for that.

**Comment by greenbigfrog** [comment]
Not sure how excessively you use this shard yourself, but it might be a good idea to add a collaborator 😛

**Pull request merged**
